### ISSUE TITLE
CSS for Visited Links

### ISSUE THREAD

**Issue by NetSpeedz** [joue-quroi/dark-theme-global#1]
What would be the CSS code for making visited links a specific color? 

Also the extension does not invert this site (https://github.com/joue-quroi/dark-theme-global/issues/new), however, when going to github.com, it is inverted. 

Would appreciate any assistance. 

------------

**Comment by joue-quroi** [comment]
> What would be the CSS code for making visited links a specific color?

```css
a:visited {
  color: red !important;
}
```

> Also the extension does not invert this site 

It does invert for me! What is your browser?

**Comment by NetSpeedz** [comment]
Are you kidding me? I posted this question over 4 months ago and you are just getting to answering? Wow! I've moved on to other solutions three times over.
